### ISSUE TITLE
Release on rubygems

### ISSUE THREAD

**Issue by danielfarrell** [sleeper/rack-auth-krb#4]
The current code has been stable for me.  It's at least a 0.1 release, but really feels more like a 0.8 or so.  Wanna increment the version and release to rubygems.org?

**Comment by sleeper** [comment]
Yep !

For sure .. I should have been done this before but was quite busy ;)
I'm going to do that before the end of the day.

Regards

**Comment by sleeper** [comment]
Should be ok now: https://rubygems.org/gems/rack-auth-krb

I let you close this issue if it works for you ;)

**Comment by danielfarrell** [comment]
Cool.  I was thinking 0.8.0, but version numbers don't really matter.  Works well, thanks!
